"""Signed Url Table added and users table updated 

Revision ID: 791e4530d524
Revises: 7064bfe94814
Create Date: 2026-02-03 11:30:13.789567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791e4530d524'
down_revision: Union[str, None] = '7064bfe94814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signed_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signed_urls_expires_at'), 'signed_urls', ['expires_at'], unique=False)
    op.create_index(op.f('ix_signed_urls_id'), 'signed_urls', ['id'], unique=False)
    op.create_index(op.f('ix_signed_urls_user_id'), 'signed_urls', ['user_id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_signed_urls_user_id'), table_name='signed_urls')
    op.drop_index(op.f('ix_signed_urls_id'), table_name='signed_urls')
    op.drop_index(op.f('ix_signed_urls_expires_at'), table_name='signed_urls')
    op.drop_table('signed_urls')
    # ### end Alembic commands ###
