"""Remove Singned url rename to file upload

Revision ID: f0cc9275f52f
Revises: 791e4530d524
Create Date: 2026-02-03 12:29:02.663578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0cc9275f52f'
down_revision: Union[str, None] = '791e4530d524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signed_urls_expires_at', table_name='signed_urls')
    op.drop_index('ix_signed_urls_id', table_name='signed_urls')
    op.drop_index('ix_signed_urls_user_id', table_name='signed_urls')
    op.drop_table('signed_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signed_urls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='signed_urls_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='signed_urls_pkey')
    )
    op.create_index('ix_signed_urls_user_id', 'signed_urls', ['user_id'], unique=False)
    op.create_index('ix_signed_urls_id', 'signed_urls', ['id'], unique=False)
    op.create_index('ix_signed_urls_expires_at', 'signed_urls', ['expires_at'], unique=False)
    # ### end Alembic commands ###
